package model;

import java.util.Date;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by c85 on 19/11/15.
 * {@link RealmObject} class to generate credential for the user.
 * Relationship with {@link Classrooms}
 * Relationship with {@link School}
 * Relationship with {@link Courses}
 * Relationship with {@link Role}
 */
public class AutoGeneratedCredential extends RealmObject{

    @PrimaryKey
    private  int autoGeneratedCredentialId;
    private String userName;
    private String password;
    private String status;
    private String academicYear;
    private School school;
    private Classrooms classroom;
    private Courses course;
    private Role role;
    private int groupStatus;
    private boolean isMySchool;
    private Date createdDate;
    private Date modifiedDate;

    public int getAutoGeneratedCredentialId() {
        return autoGeneratedCredentialId;
    }

    public void setAutoGeneratedCredentialId(int autoGeneratedCredentialId) {
        this.autoGeneratedCredentialId = autoGeneratedCredentialId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getAcademicYear() {
        return academicYear;
    }

    public void setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
    }

    public School getSchool() {
        return school;
    }

    public void setSchool(School school) {
        this.school = school;
    }

    public Classrooms getClassroom() {
        return classroom;
    }

    public void setClassroom(Classrooms classroom) {
        this.classroom = classroom;
    }

    public Courses getCourse() {
        return course;
    }

    public void setCourse(Courses course) {
        this.course = course;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public int getGroupStatus() {
        return groupStatus;
    }

    public void setGroupStatus(int groupStatus) {
        this.groupStatus = groupStatus;
    }

    public boolean isMySchool() {
        return isMySchool;
    }

    public void setIsMySchool(boolean isMySchool) {
        this.isMySchool = isMySchool;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {
        return modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}
