package model;

import java.util.Date;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by c85 on 19/11/15.
 * {@link RealmObject} class to generate credential for the user.
 * Relationship with {@link ROClassrooms}
 * Relationship with {@link ROSchool}
 * Relationship with {@link ROCourses}
 * Relationship with {@link RORole}
 */
public class ROAutoGeneratedCredential extends RealmObject {

    @PrimaryKey
    private int autoGeneratedCredentialId;
    private String userName;
    private String password;
    private String status;
    private String academicYear;
    private ROSchool roSchool;
    private ROClassrooms roClassrooms;
    private ROCourses roCourses;
    private RORole roRole;
    private int groupStatus;
    private boolean isMySchool;
    private Date createdDate;
    private Date modifiedDate;

    public int getAutoGeneratedCredentialId() {
        return autoGeneratedCredentialId;
    }

    public void setAutoGeneratedCredentialId(int autoGeneratedCredentialId) {
        this.autoGeneratedCredentialId = autoGeneratedCredentialId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getAcademicYear() {
        return academicYear;
    }

    public void setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
    }

    public ROSchool getRoSchool() {
        return roSchool;
    }

    public void setRoSchool(ROSchool roSchool) {
        this.roSchool = roSchool;
    }

    public ROClassrooms getRoClassrooms() {
        return roClassrooms;
    }

    public void setRoClassrooms(ROClassrooms roClassrooms) {
        this.roClassrooms = roClassrooms;
    }

    public ROCourses getRoCourses() {
        return roCourses;
    }

    public void setRoCourses(ROCourses roCourses) {
        this.roCourses = roCourses;
    }

    public RORole getRoRole() {
        return roRole;
    }

    public void setRoRole(RORole roRole) {
        this.roRole = roRole;
    }

    public int getGroupStatus() {
        return groupStatus;
    }

    public void setGroupStatus(int groupStatus) {
        this.groupStatus = groupStatus;
    }

    public boolean isMySchool() {
        return isMySchool;
    }

    public void setIsMySchool(boolean isMySchool) {
        this.isMySchool = isMySchool;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {
        return modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}
